name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reservation/pom.xml
          mvn clean package -f ./sender/pom.xml
          mvn clean package -f ./BoundedContext279/pom.xml
          mvn clean package -f ./BoundedContext1410/pom.xml

      - name: Docker Build and push for Reservation
        uses: docker/build-push-action@v4
        with:
          context: ./reservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation:latest
            ghcr.io/${{ github.repository }}/reservation:${{ github.ref_name }}
            
      - name: Docker Build and push for Sender
        uses: docker/build-push-action@v4
        with:
          context: ./sender
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sender:latest
            ghcr.io/${{ github.repository }}/sender:${{ github.ref_name }}
            
      - name: Docker Build and push for BoundedContext279
        uses: docker/build-push-action@v4
        with:
          context: ./BoundedContext279
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext279:latest
            ghcr.io/${{ github.repository }}/boundedcontext279:${{ github.ref_name }}
            
      - name: Docker Build and push for BoundedContext1410
        uses: docker/build-push-action@v4
        with:
          context: ./BoundedContext1410
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext1410:latest
            ghcr.io/${{ github.repository }}/boundedcontext1410:${{ github.ref_name }}
            
