server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path=/msgReqs/**, 
        - id: sender
          uri: http://localhost:8083
          predicates:
            - Path=/msgLists/**, 
        - id: BoundedContext279
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: BoundedContext1410
          uri: http://localhost:8085
          predicates:
            - Path=/stats/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/msgReqs/**, 
        - id: sender
          uri: http://sender:8080
          predicates:
            - Path=/msgLists/**, 
        - id: BoundedContext279
          uri: http://boundedContext279:8080
          predicates:
            - Path=, 
        - id: BoundedContext1410
          uri: http://boundedContext1410:8080
          predicates:
            - Path=/stats/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
